export const CONSTANTS_CONFIG = {
  UNEXPECTED_ERROR: "An Unknown error occurred, Please try again later.",
  NOT_FOUND: "The page you are looking is not found.",
  UN_AUTHORIZED: "You do not have permission to access this page.",
  ERROR_HEADING: "Error !",
  WARNING_HEADING: "Warning !!",
  SUCCESS_HEADING: "Success !!",
  ERROR_CLASS: "alert-danger",
  WARNING_CLASS: "alert-warning",
  SUCCESS_CLASS: "alert-success",
  ERROR_400_TEXT: "400: Bad request. The request is invalid or improperly formed, please verify and try again. If this issue persists, please contact (provided contact).",
  ERROR_400_TOASTR: "400: Bad request. The request is invalid or improperly formed, please verify and try again.",
  ERROR_401_TEXT: "401: Unauthorised request. Please re-authenticate and try again. If this issue persists, please contact (provided contact).",
  ERROR_401_TOASTR: "401: Unauthorised request. Please re-authenticate and try again.",
  ERROR_403_TEXT: "403: Forbidden request. The submitted request is not supported by the target service. Please contact (provided contact) for further support.",
  ERROR_403_TOASTR: "403: Forbidden request. The submitted request is not supported by the target service.",
  ERROR_404_TEXT: "404: Resource not found. The submitted request has failed because a resource associated with it cannot be found. If this issue persists, please contact (provided contact)..",
  ERROR_404_TOASTR: "404: Resource not found. The submitted request has failed because a resource associated with it cannot be found.",
  ERROR_406_TEXT: "406: Not acceptable. Request content not available or returned content not valid. Please contact (provided contact) for further support..",
  ERROR_406_TOASTR: "406: Not acceptable. Request content not available or returned content not valid.",
  ERROR_409_TEXT: "409: Conflict. The submitted request conflicts with an existing item. Please contact (provided contact) for further support.",
  ERROR_409_TOASTR: "409: Conflict. The submitted request conflicts with an existing item.",
  ERROR_412_TEXT: "412: Precondition Failed. Please try again. If issue persists, please contact (provided contact).",
  ERROR_412_TOASTR: "412: Precondition Failed. Please try again.",
  ERROR_415_TEXT: "415: Unsupported Media Type. The submitted request is in an unsupported format. Please contact (provided contact) for further support.",
  ERROR_415_TOASTR: "415: Unsupported Media Type. The submitted request is in an unsupported format.",
  ERROR_422_TEXT: "422: Unprocessable Entity. Please contact (provided contact) for further support.",
  ERROR_422_TOASTR: "422: Unprocessable Entity.",
  ERROR_424_TEXT: "424: Failed Dependency. Please contact (provided contact) for further support.",
  ERROR_424_TOASTR: "424: Failed Dependency.",
  ERROR_500_TEXT: "500: Internal Server Error. Please try again. If issue persists, please contact (provided contact).",
  ERROR_500_TOASTR: "500: Internal Server Error. Please try again.",
  ERROR_501_TEXT: "501: Not Implemented. The submitted request method is not supported. Please contact (provided contact) for further support.",
  ERROR_501_TOASTR: "501: Not Implemented. The submitted request method is not supported.",
  ERROR_503_TEXT: "503: Service Unavailable. Please contact (provided contact) for further support.",
  ERROR_503_TOASTR: "503: Service Unavailable.",
  ERROR_UNEXPECTED_TEXT: "An unexpected error has been encountered. Please contact (provided contact) for further support.",
  ERROR_UNEXPECTED_TOASTR: "Unexpected error. Please try again."
};
